### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by TT-IPIP** [FlechazoPh/QLDependency#12]
这个怎么解决
```
docker exec -it ql bash -c "$(curl -fsSL https://ghproxy.com/https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/QLOneKeyDependency.sh | sh)"
sh: line 40: 当前node版本(如果没有node，请自行安装): : command not found
sh: line 41: node: command not found
sh: line 44: 当前npm版本(如果没有npm，请自行安装): : command not found
sh: line 45: npm: command not found
sh: line 47: npm: command not found
sh: line 48: cd: /ql: No such file or directory
sh: line 49: pnpm: command not found
sh: line 51: pnpm: command not found
sh: line 53: npm: command not found
sh: line 55: pnpm: command not found
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
sh: line 59: cd: /ql/scripts/: No such file or directory
sh: line 60: cd: /ql: No such file or directory
sh: line 61: apk: command not found
sh: line 62: cd: /ql: No such file or directory
sh: line 63: apk: command not found
bash: line 3: $'\E[36m\E[0m': command not found
bash: line 3: $'1m安装依赖...\E[0m': command not found
bash: line 5: $'\E[36m\E[0m': command not found
bash: line 5: $'1m安装依赖需要时间，请耐心等待!\E[0m': command not found
bash: line 11: Requirement: command not found
bash: -c: line 12: syntax error near unexpected token `('
bash: -c: line 12: `Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests)'
```

**Comment by TT-IPIP** [comment]
执行几秒就完了，依赖一个没装上

**Comment by FlechazoPh** [comment]
去搜索一下怎么安装 node和npm

**Comment by TT-IPIP** [comment]
node和npm 是容器外安装还是容器内安装

**Comment by FlechazoPh** [comment]
在容器内安装，安装完之后 node -v , npm -v 查看node版本，是否安装成功

**Comment by TT-IPIP** [comment]
root@20b4ca617588:/ql $ node -v
v16.13.1
root@20b4ca617588:/ql $ npm -v
8.1.2
root@20b4ca617588:/ql $ docker exec -it ql bash -c "$(curl -fsSL https://ghproxy.com/https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/QLOneKeyDependency.sh | sh)"
sh: 当前node版本(如果没有node，请自行安装): : not found
sh: 当前npm版本(如果没有npm，请自行安装): : not found
ERROR: unable to select packages:
ERROR: unable to select packages:
ERROR: unable to select packages:
bash: docker: command not found
root@20b4ca617588:/ql $

**Comment by TT-IPIP** [comment]
root@20b4ca617588:/ql $ node -v
v16.13.1
root@20b4ca617588:/ql $ npm -v
8.1.2
root@20b4ca617588:/ql $ docker exec -it ql bash -c "$(curl -fsSL https://ghproxy.com/https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/QLOneKeyDependency.sh | sh)"
sh: 当前node版本(如果没有node，请自行安装): : not found
sh: 当前npm版本(如果没有npm，请自行安装): : not found
ERROR: unable to select packages:
ERROR: unable to select packages:
ERROR: unable to select packages:
bash: docker: command not found
root@20b4ca617588:/ql $

**Comment by FlechazoPh** [comment]
先进容器在执行命令，分开执行

**Comment by TT-IPIP** [comment]
root@2df71616abed:/ql $ curl -fsSL https://ghproxy.com/https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/QLOneKeyDependency.sh | sh



 安装依赖...

 安装依赖需要时间，请耐心等待!




sh: 当前node版本(如果没有node，请自行安装): : not found
v16.13.1

sh: 当前npm版本(如果没有npm，请自行安装): : not found
8.1.2
Nothing to stop. No server is running for the store at /root/.pnpm-store/v3
 ERR_PNPM_REGISTRIES_MISMATCH  This modules directory was created using the following registries configuration: {"default":"https://registry.npmjs.org/"}. The current configuration is {"default":"https://registry.npm.taobao.org/"}. To recreate the modules directory using the new settings, run "pnpm install".
Recreating /usr/local/pnpm-global/5/node_modules

   ╭──────────────────────────────────────────────────────────────────╮
   │                                                                  │
   │                Update available! 6.24.2 → 6.26.1.                │
   │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v6.26.1   │
   │                 Run pnpm add -g pnpm to update.                  │
   │                                                                  │
   │      Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
   │                                                                  │
   ╰──────────────────────────────────────────────────────────────────╯

Lockfile is up-to-date, resolution step is skipped
Packages: +192
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /root/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 192, reused 90, downloaded 102, added 192, done

added 124 packages, removed 18 packages, and changed 107 packages in 23s

12 packages are looking for funding
  run `npm fund` for details
Packages: +10 -3
++++++++++---
Progress: resolved 200, reused 194, downloaded 5, added 10, done
 WARN  js-base64 has no binaries
 WARN  silly-datetime has no binaries

/usr/local/pnpm-global/5:
+ js-base64 3.7.2
+ qrcode-terminal 0.12.0
+ silly-datetime 0.1.2

 WARN  Issues with peer dependencies found
.
└─┬ ts-node
  └── ✕ missing peer @types/node@"*"
Peer dependencies that should be installed:
  @types/node@"*"  
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: requests in /usr/lib/python3.8/site-packages (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3.8/site-packages (from requests) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3.8/site-packages (from requests) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.8/site-packages (from requests) (2020.4.5.1)
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]

 依赖安装完毕...建议重启 Docker 

 有任何问题，请在此仓库提交Issue： https://github.com/FlechazoPh/QLDependency

root@2df71616abed:/ql $

**Comment by FlechazoPh** [comment]
源镜像有问题， 参考解决方案： [fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz超时](https://blog.csdn.net/weixin_43905458/article/details/106738812)
如果你的 VPS 是海外的，可以把源替换成国外源试试

**Comment by TT-IPIP** [comment]
是国内机Debian10系统

**Comment by FlechazoPh** [comment]
> 是国内机Debian10系统

暂时没用 Debian 测试过，CentOS正常

**Comment by TT-IPIP** [comment]
容器是alpine系统
