### ISSUE TITLE
请教一下，拉取安装的时候出现如图这个问题该怎么解决它呢？

### ISSUE THREAD

**Issue by China-Huanghe** [FlechazoPh/QLDependency#14]
![截图_20221425031440](https://user-images.githubusercontent.com/77739994/155671445-a84fe8c9-d6a1-4b2e-94cc-2106048c1cf3.png)

**Comment by yangwangkong** [comment]
我只能说这脚本建议进到docker里边去运行，我的树莓派4B也是这样，进去就能用了

**Comment by China-Huanghe** [comment]
> 我说这个脚本建议进到码头里边去运行，我的树莓派4B也是这样，进去只能用了

nice，按照你的办法装好了，但是安装过程中会有些报错警告之类的，不清楚是什么问题导致的

**Comment by yangwangkong** [comment]
> > 我说这个脚本建议进到码头里边去运行，我的树莓派4B也是这样，进去只能用了
> 
> nice，按照你的办法装好了，但是安装过程中会有些报错警告之类的，不清楚是什么问题导致的

我也有挺多报错，但不影响脚本使用就是了
