### ISSUE TITLE
群晖918+的DOCKER使用脚本无法安装青龙依赖库

### ISSUE THREAD

**Issue by hookhuang** [FlechazoPh/QLDependency#15]
**Describe the bug**
群晖918+的DOCKER使用脚本无法安装青龙依赖库
设备：群晖918+
DSM版本：7.0

**To Reproduce**
1. 通过SSH登录群晖
2. 给账户提权后,输入   docker exec -it qinglong bash
3. 进入青龙的docker后输入  curl -fsSL https://ghproxy.com/https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/QLOneKeyDependency.sh | sh
4. 在青龙面板的“依赖管理”里面看不到有任何的依赖库文件，在执行脚本时有找不到依整库的问题。

**Screenshots**
![执行脚本反馈-1](https://user-images.githubusercontent.com/56341028/157199111-f894ad6d-dc04-4145-b383-343800d31b56.jpg)
![执行脚本反馈](https://user-images.githubusercontent.com/56341028/157199154-4331197c-aacc-4a73-9ca7-c46b960f9b1f.jpg)
![执行脚本反馈-3](https://user-images.githubusercontent.com/56341028/157199444-8180c68d-3c4f-4880-8679-9a2cc0ed3b53.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10 ]
 - Browser [chrome]

**Additional context**

**Comment by FlechazoPh** [comment]
原因是没有node环境，导致依赖安装失败，可以参考如下文档先安装node环境： https://segmentfault.com/a/1190000039973959 
**注意要先进入容器再安装 node 环境**

**Comment by hookhuang** [comment]
> 原因是没有node环境，导致依赖安装失败，可以参考如下文档先安装node环境： https://segmentfault.com/a/1190000039973959 **注意要先进入容器再安装 node 环境**

谢谢解答，初步认为是node.js和npm没有安装的原因，而在检查后，发现容器中是有node.js和npm的，只不过容器的路径配置问题，查找到在/usr/bin下的npm是能运行，而/usr/local/bin下面的npm执行没有响应的（也这是之前脚本运行没有返回的原因），把/usr/bin:放到青龙容器的路径最前面后，问题解决。

**Comment by bbcjd123** [comment]
> > 原因是没有node环境，导致依赖安装失败，可以参考如下文档先安装node环境： https://segmentfault.com/a/1190000039973959 **注意要先进入容器再安装 node 环境**
> 
> 谢谢解答，初步认为是node.js和npm没有安装的原因，而在检查后，发现容器中是有node.js和npm的，只不过容器的路径配置问题，查找到在/usr/bin下的npm是能运行，而/usr/local/bin下面的npm执行没有响应的（也这是之前脚本运行没有返回的原因），把/usr/bin:放到青龙容器的路径最前面后，问题解决。

和你一模一样的问题，我是群晖220+，路径怎么配置呀，能细说吗？谢谢

**Comment by zailushang2008** [comment]
和你一模一样的问题和一样的型号，路径怎么配置呀，能细说吗？谢谢

**Comment by zlkent** [comment]
> 和你一模一样的问题和一样的型号，路径怎么配置呀，能细说吗？谢谢

进到群晖-Docker-容器-找到你的青龙容器，停止，编辑，高级设置里的环境，变量PATH的值里，开头加上/usr/bin:

最后看起来应该是这样的/usr/bin:/usr/local/sbin:/......（后面省略）

**Comment by lniaen** [comment]
> > 和你一模一样的问题和一样的型号，路径怎么配置呀，能细说吗？谢谢
> 
> 进到群晖-Docker-容器-找到你的青龙容器，停止，编辑，高级设置里的环境，变量PATH的值里，开头加上/usr/bin:
> 
> 最后看起来应该是这样的/usr/bin:/usr/local/sbin:/......（后面省略）

`echo $PATH`后，/usr/bin:路径已经包含在内，
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.local/share/pnpm:/root/.local/share/pnpm/global/5/node_modules:`
所以目前来说应该不是路径的问题。
使用软链接到/usr/local/bin后问题依旧，有可能是版本问题了……
