### ISSUE TITLE
安装不了。

### ISSUE THREAD

**Issue by happyaguang** [FlechazoPh/QLDependency#16]
用 node -v  和  npm -v 都可以显示版本号。
 node 14.18.3， npm 5.6.0
但运行命令就是安装不了，提示
sh: 当前node版本(如果没有node，请自行安装): : not found
sh: 当前npm版本(如果没有npm，请自行安装): : not found
我用的R4S openwrt docker

**Comment by BillScott1024** [comment]
参考此Issue： #15   https://github.com/FlechazoPh/QLDependency/issues/15#issuecomment-1061792648
