### ISSUE TITLE
一键安装依赖成功后，青龙面板依赖管理中需要重复安装吗吗？

### ISSUE THREAD

**Issue by Mait31** [FlechazoPh/QLDependency#18]
我使用一键安装依赖命名并显示安装成功，但是面板依赖管理中没有显示安装的依赖，我不知道这两者之间有什么关系嘛？

**Comment by BillScott1024** [comment]
面板依赖管理中不会显示，不影响使用

**Comment by FlechazoPh** [comment]
依赖可以正常使用，不显示没关系

**Comment by huxiuqiangwei2021** [comment]
大佬，我也是和上面这位老兄一样的情况，SSH进到群晖docker里，按教程安装，看到在下载，比如413MB，（1/117）这些信息，最后输出日志显示依赖安装成功，但是qinglong面板的依赖管理里面还是空的，试着跑了一个定时任务，日志还是显示“Error: Cannot find module 'jsdom'
Require stack:”，这个样子。

**Comment by FlechazoPh** [comment]
> 大佬，我也是和上面这位老兄一样的情况，SSH进到群晖docker里，按教程安装，看到在下载，比如413MB，（1/117）这些信息，最后输出日志显示依赖安装成功，但是qinglong面板的依赖管理里面还是空的，试着跑了一个定时任务，日志还是显示“Error: Cannot find module 'jsdom'
> Require stack:”，这个样子。

青龙版本是多少

**Comment by huxiuqiangwei2021** [comment]
大佬，青龙版本是2.13.1，在群晖里用docker装的，Faker2的库

**Comment by FlechazoPh** [comment]
@huxiuqiangwei2021 用新的脚本试试，看下文档

**Comment by huxiuqiangwei2021** [comment]
好的，我试一下，有结果了还是来这个帖子反馈哈

**Comment by huxiuqiangwei2021** [comment]
大佬，经过我试验，发现几个比较关键的点：1、青龙2.13.1需要用您提到的新的脚本安装依赖才行 2、https://ghproxy.com/这个加速代理网站大佬因为服务器的压力，封禁了大部分的JD仓库，所以照搬一些以这个前缀为开头的命令是不行了，需要另找能连接上的前缀 3、使用一键安装依赖的脚本，仍然需要通过手工运行命令进行安装pnmp（还是qnpm还是qnmp来着）？好像是这个东西 4、使用一键安装脚本的时候，提示要自行安装node和pnmp（还是qnpm还是qnmp来着），我的群晖环境里套件就有node和node.js,但是这个docker里装的青龙好像需要再装node？暂时没想明白，没有装这个node，只是手工装了pnmp（还是qnpm还是qnmp来着），好像目前没发现什么大的问题，看起来正常跑起来了 5、一键脚本安装好依赖以后，青龙面板的依赖管理里面仍然看不到。但似乎是能用。

**Comment by chancat87** [comment]
我碰到的问题是，在青龙后台安装依赖，node,py3都安装上了，linux那几个依赖除了gcc成功，其他怎么都安装不上。然后用一键依赖显示倒是没有出错，但是进入青龙后台，node的依赖全部失败，再怎么安装也不行了，重装青龙也不行。。

**Comment by MiaoMFoo** [comment]
> 我碰到的问题是，在青龙后台安装依赖，node,py3都安装上了，linux那几个依赖除了gcc成功，其他怎么都安装不上。然后用一键依赖显示倒是没有出错，但是进入青龙后台，node的依赖全部失败，再怎么安装也不行了，重装青龙也不行。。

我也是，求解决方法
