### ISSUE TITLE
最新的2.12.1显示无法cd ql/scripts

### ISSUE THREAD

**Issue by shallowdream233** [FlechazoPh/QLDependency#19]
![bug](https://user-images.githubusercontent.com/64050521/163120554-cdfdb52f-516f-4a8a-9c2e-dac5b72eb1b5.png)

**Comment by WenJimmy** [comment]
新版移动到/ql/data/scripts 目录下了，做下适配吧

**Comment by FlechazoPh** [comment]
已更新
