### ISSUE TITLE
报错：ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by immoke** [FlechazoPh/QLDependency#21]
您好，我进入docker内，执行后报错，报错信息如下：

环境：纯净Centos7 2009

`root@qinglong:/ql $ curl -fsSL https://ghproxy.com/https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/QLOneKeyDependency.sh | sh

 安装依赖...

 安装依赖需要时间，请耐心等待!

sh: 当前node版本(如果没有node，请自行安装): : not found
v17.8.0

sh: 当前npm版本(如果没有npm，请自行安装): : not found
8.7.0
Nothing to stop. No server is running for the store at /root/.pnpm-store/v3
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Packages: +1
+
Progress: resolved 201, reused 199, downloaded 1, added 1, done

/usr/local/pnpm-global/5:
+ pnpm 6.32.9

 WARN  Issues with peer dependencies found
.
└─┬ ts-node
  └── ✕ missing peer @types/node@"*"
Peer dependencies that should be installed:
  @types/node@"*"
Lockfile is up-to-date, resolution step is skipped
Already up-to-date

changed 207 packages in 26s

10 packages are looking for funding
  run `npm fund` for details
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Already up-to-date
 WARN  js-base64 has no binaries
 WARN  silly-datetime has no binaries
Progress: resolved 201, reused 200, downloaded 0, added 0, done
 WARN  Issues with peer dependencies found
.
└─┬ ts-node
  └── ✕ missing peer @types/node@"*"
Peer dependencies that should be installed:
  @types/node@"*"
Requirement already satisfied: requests in /usr/lib/python3.9/site-packages (2.26.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.9/site-packages (from requests) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.9/site-packages (from requests) (2020.12.5)
Requirement already satisfied: charset_normalizer~=2.0.0 in /usr/lib/python3.9/site-packages (from requests) (2.0.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.9/site-packages (from requests) (3.3)
fetch https://mirrors.aliyun.com/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.aliyun.com/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
OK: 491 MiB in 213 packages
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   dev react@"17.x" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=15.5 <=16.x" from react-codemirror2@7.2.1
npm ERR! node_modules/react-codemirror2
npm ERR!   dev react-codemirror2@"^7.2.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-24T07_10_39_844Z-debug-0.log
fetch https://mirrors.aliyun.com/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.aliyun.com/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
OK: 491 MiB in 213 packages
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   dev react@"17.x" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=15.5 <=16.x" from react-codemirror2@7.2.1
npm ERR! node_modules/react-codemirror2
npm ERR!   dev react-codemirror2@"^7.2.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /root/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-24T07_10_51_354Z-debug-0.log
OK: 491 MiB in 213 packages

 依赖安装完毕...建议重启 Docker

 有任何问题，请在此仓库提交Issue： https://github.com/FlechazoPh/QLDependency

root@qinglong:/ql $`

**Comment by FlechazoPh** [comment]
青龙版本贴一下

**Comment by immoke** [comment]
青龙版本 v2.12.1

**Comment by FlechazoPh** [comment]
试下新脚本，兼容了新版本青龙

**Comment by as7212325** [comment]
直接进入qinglong bash 执行
`curl -fsSL https://ghproxy.fsofso.com/https://github.com/FlechazoPh/QLDependency/blob/main/Shell/XinQLOneKey.sh | sh`

**Comment by FlechazoPh** [comment]
@as7212325 正解

**Comment by Matrix-Chen** [comment]
我也遇到了类似的问题，在armbian内核5.15.73下运行安装依赖命令的结果如下：
root@armbian:~# uname -a
Linux armbian 5.15.73-flippy-78+o #183 SMP PREEMPT Wed Oct 12 22:08:04 CST 2022 
aarch64 aarch64 aarch64 GNU/Linux

root@armbian:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

root@qinglong:/ql $ curl -fsSL https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/XinQLOneKey.sh | sh

 安装依赖...

 安装依赖需要时间，请耐心等待!

sh: 当前node版本(如果没有node，请自行安装): : not found
v16.16.0

sh: 当前npm版本(如果没有npm，请自行安装): : not found
8.19.2
Nothing to stop. No server is running for the store at /root/.local/share/pnpm/store/v3
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, whichis known to be problematic.  See https://v8.dev/blog/math-random for details.
Already up to date
Progress: resolved 202, reused 201, downloaded 0, added 0, done
 WARN  Issues with peer dependencies found
.
└─┬ ts-node 10.9.1
  └── ✕ missing peer @types/node@"*"
Peer dependencies that should be installed:
  @types/node@"*"

Done in 13.6s
Lockfile is up to date, resolution step is skipped
Already up to date
Done in 7.2s

changed 211 packages in 2m

11 packages are looking for funding
  run `npm fund` for details
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, whichis known to be problematic.  See https://v8.dev/blog/math-random for details.
Already up to date
Progress: resolved 202, reused 201, downloaded 0, added 0, done
 WARN  js-base64 has no binaries
 WARN  silly-datetime has no binaries
 WARN  Issues with peer dependencies found
.
└─┬ ts-node 10.9.1
  └── ✕ missing peer @types/node@"*"
Peer dependencies that should be installed:
  @types/node@"*"

Done in 12.5s
Looking in indexes: https://pypi.doubanio.com/simple/
Requirement already satisfied: requests in /usr/local/lib/python3.10/site-packages (2.28.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests) (2022.9.24)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests) (1.26.12)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.10/site-packages (from requests) (2.1.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
fetch https://mirrors.aliyun.com/alpine/v3.16/main/aarch64/APKINDEX.tar.gz
fetch https://mirrors.aliyun.com/alpine/v3.16/community/aarch64/APKINDEX.tar.gz
OK: 493 MiB in 177 packages
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: content-disposition@0.5.4
npm WARN Found: peer eslint-plugin-import@">=2.18.0" from eslint-config-standard@13.0.1
npm WARN node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"13.0.1" from content-disposition@0.5.4
npm WARN   node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-import@">=2.18.0" from eslint-config-standard@13.0.1
npm WARN node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"13.0.1" from content-disposition@0.5.4
npm WARN   node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-19T02_04_37_732Z-debug-0.log
fetch https://mirrors.aliyun.com/alpine/v3.16/main/aarch64/APKINDEX.tar.gz
fetch https://mirrors.aliyun.com/alpine/v3.16/community/aarch64/APKINDEX.tar.gz
OK: 493 MiB in 177 packages
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: content-disposition@0.5.4
npm WARN Found: peer eslint-plugin-import@">=2.18.0" from eslint-config-standard@13.0.1
npm WARN node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"13.0.1" from content-disposition@0.5.4
npm WARN   node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-import@">=2.18.0" from eslint-config-standard@13.0.1
npm WARN node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"13.0.1" from content-disposition@0.5.4
npm WARN   node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: content-disposition@0.5.4
npm WARN Found: peer eslint-plugin-standard@">=4.0.0" from eslint-config-standard@13.0.1
npm WARN node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"13.0.1" from content-disposition@0.5.4
npm WARN   node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-standard@">=4.0.0" from eslint-config-standard@13.0.1
npm WARN node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"13.0.1" from content-disposition@0.5.4
npm WARN   node_modules/.pnpm/content-disposition@0.5.4/node_modules/content-disposition
npm WARN ERESOLVE overriding peer dependency
npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-10-19T02_10_49_307Z-debug-0.log
fetch https://mirrors.aliyun.com/alpine/v3.16/main/aarch64/APKINDEX.tar.gz
fetch https://mirrors.aliyun.com/alpine/v3.16/community/aarch64/APKINDEX.tar.gz
OK: 493 MiB in 177 packages

 依赖安装完毕...建议重启 Docker

 有任何问题，请在此仓库提交Issue： https://github.com/FlechazoPh/QLDependency
