### ISSUE TITLE
群晖docker不能安装使用

### ISSUE THREAD

**Issue by zailushang2008** [FlechazoPh/QLDependency#22]
日记：
root@qinglong:/ql $ cd /usr/bin
root@qinglong:/usr/bin $ npm -v
8.5.5
root@qinglong:/usr/bin $ cd /
root@qinglong:/ $ CD
bash: CD: command not found
root@qinglong:/ $ cd
root@qinglong:~ $ node -v
v17.8.0
root@qinglong:~ $ npm -v
8.5.5
root@qinglong:~ $ docker exec -it qinglong bash -c "$(curl -fsSL https://ghproxy.com/https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/QLOneKeyDependency.sh | sh)"
sh: 当前node版本(如果没有node，请自行安装): : not found

**Comment by zailushang2008** [comment]
https://github.com/FlechazoPh/QLDependency/issues/15，这个的没有说清楚，能详细说下吗？

**Comment by FlechazoPh** [comment]
贴一下青龙版本号

**Comment by VFengChen** [comment]
> 贴一下青龙版本号

青龙面板v2.13.3一样问题

**Comment by FlechazoPh** [comment]
直接在docker容器内 执行 ``sh https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/QLOneKeyDependency.sh``
