### ISSUE TITLE
node 和npm 都安装了 还是出错

### ISSUE THREAD

**Issue by fckcg** [FlechazoPh/QLDependency#23]
root@qinglong:/ql $ docker exec -it qinglong bash -c "$(curl -fsSL https://ghprox
y.com/https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/QLOneK
eyDependency.sh | sh)"
sh: 当前node版本(如果没有node，请自行安装): : not found
sh: 当前npm版本(如果没有npm，请自行安装): : not found
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.1.1; however, version 22.0.4 is available.
You should consider upgrading via the '/usr/bin/python3.8 -m pip install --upgrade pip' command.
ERROR: unable to select packages:
ERROR: unable to select packages:
ERROR: unable to select packages:
/bin/sh: docker: not found

**Comment by fckcg** [comment]
sh: 当前node版本(如果没有node，请自行安装): : not found
sh: 当前npm版本(如果没有npm，请自行安装): : not found
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
ERROR: unable to select packages:
ERROR: unable to select packages:
ERROR: unable to select packages:
/bin/sh: docker: not found

**Comment by FlechazoPh** [comment]
先进入青龙容器，安装下node和npm环境，具体步骤google即可

**Comment by wenzhuo4657** [comment]
> 先进入青龙容器，安装下node和npm环境，具体步骤google即可

离谱，我进了容器都能调用help，他就是找不到
root@qinglong:/ql $ npm version
{
  npm: '9.6.6',
  node: '18.16.1',
  acorn: '8.8.2',
  ada: '1.0.4',
  ares: '1.19.1',
  brotli: '1.0.9',
  cldr: '43.1',
  icu: '73.2',
  llhttp: '6.0.11',
  modules: '108',
  napi: '8',
  nghttp2: '1.53.0',
  openssl: '3.1.1',
  simdutf: '3.2.2',
  tz: '2023c',
  undici: '5.21.0',
  unicode: '15.0',
  uv: '1.44.2',
  uvwasi: '0.0.15',
  v8: '10.2.154.26-node.26',
  zlib: '1.2.13'
}
