### ISSUE TITLE
一键脚本报错，请求帮忙

### ISSUE THREAD

**Issue by immoke** [FlechazoPh/QLDependency#25]
环境：
CentOS7_2009
docker -v：Docker version 1.13.1, build 7d71120/1.13.1
青龙面板最新：v2.13.3
浏览器：Chrome/101.0.0.0
操作系统：Windows11
网络：香港出口

报错日志：
[root@centos7-2009-uefi-6 opt]# docker exec -it qinglong bash
root@qinglong:/ql $ curl -fsSL https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/XinQLOneKey.sh | sh

 安装依赖...

 安装依赖需要时间，请耐心等待!

sh: 当前node版本(如果没有node，请自行安装): : not found
v18.3.0

sh: 当前npm版本(如果没有npm，请自行安装): : not found
8.12.1
Nothing to stop. No server is running for the store at /root/.local/share/pnpm/store/v3
The location of the currently running pnpm differs from the location where pnpm will be installed
 Current pnpm location: /usr/local/bin
 Target location: /root/.local/share/pnpm

 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Already up-to-date
 WARN  Issues with peer dependencies found
.
└─┬ ts-node
  └── ✕ missing peer @types/node@"*"
Peer dependencies that should be installed:
  @types/node@"*"

Progress: resolved 204, reused 203, downloaded 0, added 0, done
Lockfile is up-to-date, resolution step is skipped
Already up-to-date

changed 208 packages in 20s

11 packages are looking for funding
  run `npm fund` for details
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Already up-to-date
Progress: resolved 204, reused 203, downloaded 0, added 0, done
 WARN  js-base64 has no binaries
 WARN  silly-datetime has no binaries
 WARN  Issues with peer dependencies found
.
└─┬ ts-node
  └── ✕ missing peer @types/node@"*"
Peer dependencies that should be installed:
  @types/node@"*"
Requirement already satisfied: requests in /usr/lib/python3.10/site-packages (2.28.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.10/site-packages (from requests) (2022.5.18.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.10/site-packages (from requests) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/lib/python3.10/site-packages (from requests) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.10/site-packages (from requests) (1.26.9)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
fetch https://mirrors.aliyun.com/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.aliyun.com/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
OK: 452 MiB in 177 packages
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: content-disposition@0.5.4
npm WARN Found: peer eslint-plugin-import@">=2.18.0" from eslint-config-standard@13.0.1
npm WARN node_modules/.pnpm/registry.npmmirror.com+content-disposition@0.5.4/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"13.0.1" from content-disposition@0.5.4
npm WARN   node_modules/.pnpm/registry.npmmirror.com+content-disposition@0.5.4/node_modules/content-disposition
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-import@">=2.18.0" from eslint-config-standard@13.0.1
npm WARN node_modules/.pnpm/registry.npmmirror.com+content-disposition@0.5.4/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"13.0.1" from content-disposition@0.5.4
npm WARN   node_modules/.pnpm/registry.npmmirror.com+content-disposition@0.5.4/node_modules/content-disposition
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-15T02_48_59_838Z-debug-0.log
fetch https://mirrors.aliyun.com/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.aliyun.com/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
OK: 452 MiB in 177 packages
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: content-disposition@0.5.4
npm WARN Found: peer eslint-plugin-import@">=2.18.0" from eslint-config-standard@13.0.1
npm WARN node_modules/.pnpm/registry.npmmirror.com+content-disposition@0.5.4/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"13.0.1" from content-disposition@0.5.4
npm WARN   node_modules/.pnpm/registry.npmmirror.com+content-disposition@0.5.4/node_modules/content-disposition
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-import@">=2.18.0" from eslint-config-standard@13.0.1
npm WARN node_modules/.pnpm/registry.npmmirror.com+content-disposition@0.5.4/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"13.0.1" from content-disposition@0.5.4
npm WARN   node_modules/.pnpm/registry.npmmirror.com+content-disposition@0.5.4/node_modules/content-disposition
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: content-disposition@0.5.4
npm WARN Found: peer eslint-plugin-standard@">=4.0.0" from eslint-config-standard@13.0.1
npm WARN node_modules/.pnpm/registry.npmmirror.com+content-disposition@0.5.4/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"13.0.1" from content-disposition@0.5.4
npm WARN   node_modules/.pnpm/registry.npmmirror.com+content-disposition@0.5.4/node_modules/content-disposition
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer eslint-plugin-standard@">=4.0.0" from eslint-config-standard@13.0.1
npm WARN node_modules/.pnpm/registry.npmmirror.com+content-disposition@0.5.4/node_modules/content-disposition/node_modules/eslint-config-standard
npm WARN   dev eslint-config-standard@"13.0.1" from content-disposition@0.5.4
npm WARN   node_modules/.pnpm/registry.npmmirror.com+content-disposition@0.5.4/node_modules/content-disposition
npm WARN ERESOLVE overriding peer dependency
npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-15T02_51_08_801Z-debug-0.log
OK: 452 MiB in 177 packages

 依赖安装完毕...建议重启 Docker

 有任何问题，请在此仓库提交Issue： https://github.com/FlechazoPh/QLDependency

**Comment by FlechazoPh** [comment]
WARN 是警告，不影响使用就不用管，最后面的ERR是哪个包没装上，可以再查看下详细日志

**Comment by immoke** [comment]
您好，日志有些大，我刚才用最新的脚本又重新跑了一遍，还是报错。
我把这两次的错误日志全部打包了，麻烦帮忙看一下，谢谢。
https://tbds.imoke.org:5001/sharing/40XjNhzmm

**Comment by FlechazoPh** [comment]
尝试下手动安装没正确安装上的依赖，这个报错应该只影响某几个以来的安装
