### ISSUE TITLE
报错日志显示 not found 参考解决方案，要先安装npm和node

### ISSUE THREAD

**Issue by FlechazoPh** [FlechazoPh/QLDependency#27]
要先安装npm和node
1、cd /usr/local  && wget https://nodejs.org/dist/v14.17.5/node-v14.17.5-linux-x64.tar.xz    
2、xz -dk node-v14.17.5-linux-x64.tar.xz  && tar -xvf node-v14.17.5-linux-x64.tar   
3、复制下面放到profile文件
export NODE_HOME=/usr/local/node-v14.17.5-linux-x64
export PATH=$PATH:$NODE_HOME/bin
export NODE_PATH=$NODE_HOME/lib/node_modules
 
生效
source /etc/profile
4、然后docker exec -it 容器名 bash
5、curl -fsSL https://ghproxy.com/https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/QLOneKeyDependency.sh | sh
运行这个命令就可以了

之前就算装了npm和node，直接运行一键命令还是会报错，今天换了这个方法，先进容器再运行就没啥问题，不过还是有两个地方报错了
![QQ截图20211121150318](https://user-images.githubusercontent.com/94167806/142753005-6fbdf1f0-437a-43b8-a073-4606fc4205f3.png)
图中提到的日志保存文件目录/root/.npm/    我在宝塔里面没有找到，日志文件也没有搜索到

_Originally posted by @naiveclub in https://github.com/FlechazoPh/QLDependency/issues/5#issuecomment-974767118_

**Comment by liwenjie119** [comment]
日志保存文件目录/root/.npm...是指docker内的目录
![image](https://user-images.githubusercontent.com/25956275/174927043-3404709a-1b9e-4fc3-8eaa-7eae2af8714c.png)

**Comment by FlechazoPh** [comment]
可能某个依赖版本有问题，能正常运行不影响就先不用管

**Comment by OpsDarren** [comment]
> source /etc/profile

`1、cd /usr/local && wget https://nodejs.org/dist/v14.17.5/node-v14.17.5-linux-x64.tar.xz
2、xz -dk node-v14.17.5-linux-x64.tar.xz && tar -xvf node-v14.17.5-linux-x64.tar
3、复制下面放到profile文件
export NODE_HOME=/usr/local/node-v14.17.5-linux-x64
export PATH=$PATH:$NODE_HOME/bin
export NODE_PATH=$NODE_HOME/lib/node_modules

生效
source /etc/profile`

请问一下大佬，以上这部分内容是在docker宿主机执行吗，我好像执行了之后，在qinglong容器内执行依赖脚本依然会显示
sh: 当前node版本(如果没有node，请自行安装): : not found
v16.16.0

sh: 当前npm版本(如果没有npm，请自行安装): : not found
8.19.1

**Comment by naiveclub** [comment]
> 

你可以在青龙面板里面安装依赖；
你这个错误表示没有找到16.16.0的node版本，应该是你用的脚本限制了node版本必须为16.16？

**Comment by OpsDarren** [comment]
> > 
> 
> 你可以在青龙面板里面安装依赖； 你这个错误表示没有找到16.16.0的node版本，应该是你用的脚本限制了node版本必须为16.16？

我是直接用了这个

【更新】 版本号 2.12+ 的新版本青龙安装失败请尝试：
`
docker exec -it qinglong bash -c "$(curl -fsSL https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/XinQLOneKey.sh | sh)"
`
