### ISSUE TITLE
群晖 ds3615xs 7.0.1 update3 青龙版本 2.13.3 用新版本脚本安装出错:

### ISSUE THREAD

**Issue by lukemin** [FlechazoPh/QLDependency#28]
群晖 ds3615xs 7.0.1 update3 青龙版本 2.13.3 用新版本脚本安装出错:
ash-4.4# docker exec -it qinglong bash -c "$(curl -fsSL https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/XinQLOneKey.sh | sh)"

sh: line 40: 当前node版本(如果没有node，请自行安装): : command not found
sh: line 44: 当前npm版本(如果没有npm，请自行安装): : command not found
sh: line 48: cd: /ql: No such file or directory
sh: line 49: pnpm: command not found
sh: line 51: pnpm: command not found
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'jsdom@20.0.0',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.7', npm: '8.12.2' }
npm WARN EBADENGINE }
sh: line 55: pnpm: command not found
sh: line 57: pip3: command not found
sh: line 59: cd: /ql/data/scripts/: No such file or directory
sh: line 60: cd: /ql: No such file or directory
sh: line 61: apk: command not found
sh: line 62: cd: /ql: No such file or directory
sh: line 63: apk: command not found
bash: line 4: $'\E[36m\E[0m': command not found
bash: line 4: $'1m安装依赖...\E[0m': command not found
bash: line 6: $'\E[36m\E[0m': command not found
bash: line 6: $'1m安装依赖需要时间，请耐心等待!\E[0m': command not found
bash: line 11: v12.22.7: command not found
bash: line 13: 8.12.2: command not found
bash: line 15: added: command not found
bash: line 17: 11: command not found
bash: line 18: run: command not found
bash: line 20: $'\E[36m\E[0m': command not found
bash: line 20: 1m依赖安装完毕...建议重启: command not found
bash: line 22: $'\E[36m\E[0m': command not found
bash: line 22: 1m有任何问题，请在此仓库提交Issue：: command not found

**Comment by FlechazoPh** [comment]
没有node，环境，参考其他issue先安装node环境
