### ISSUE TITLE
n1 docker脚本报错

### ISSUE THREAD

**Issue by qicheBoy** [FlechazoPh/QLDependency#30]
环境：
斐讯N1 openwrt flippy-71+o
docker ：Docker version 20.10.14, build a224086
青龙面板：v2.11.0
浏览器：Microsoft Edge
操作系统：Windows10

报错日志：
root@qinglong:/ql $ curl -fsSL https://raw.githubusercontent.com/shufflewzc/QLDependency/main/Shell/QLOneKeyDependency.sh | sh

 安装依赖...

 安装依赖需要时间，请耐心等待!

sh: 当前node版本(如果没有node，请自行安装): : not found
v16.13.1

sh: 当前npm版本(如果没有npm，请自行安装): : not found
8.13.2
Nothing to stop. No server is running for the store at /root/.pnpm-store/v3
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Packages: +1
+
Progress: resolved 198, reused 196, downloaded 1, added 1, done

/usr/local/pnpm-global/5:
+ pnpm 7.4.1

 WARN  Issues with peer dependencies found
.
└─┬ ts-node
  └── ✕ missing peer @types/node@"*"
Peer dependencies that should be installed:
  @types/node@"*"  
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.

removed 1 package, and changed 208 packages in 2m

11 packages are looking for funding
  run `npm fund` for details
 ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: requests in /usr/lib/python3.8/site-packages (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3.8/site-packages (from requests) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3.8/site-packages (from requests) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.8/site-packages (from requests) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.8/site-packages (from requests) (2020.4.5.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main/aarch64/APKINDEX.tar.gz
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/community/aarch64/APKINDEX.tar.gz
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main/aarch64/APKINDEX.tar.gz
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/community/aarch64/APKINDEX.tar.gz
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  lxml (no such package):
    required by: world[lxml]

**Comment by FlechazoPh** [comment]
进容器后，试下 `` pnpm setup `` 命令

**Comment by FlechazoPh** [comment]
> 进容器后，试下 `pnpm setup` 命令
