### ISSUE TITLE
青龙全依赖 老是报这个

### ISSUE THREAD

**Issue by 886k** [FlechazoPh/QLDependency#43]
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

怎么办弄一下下午啦，求个详情解决方式

<img width="560" alt="image" src="https://user-images.githubusercontent.com/115762192/232287820-7f6e50d7-572f-4f8f-b8eb-2ebfd3841414.png">

**Comment by FlechazoPh** [comment]
warning 可以不用处理
