### ISSUE TITLE
安装依赖时报错

### ISSUE THREAD

**Issue by 886k** [FlechazoPh/QLDependency#44]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   dev react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @monaco-editor/react@4.2.1
npm ERR! node_modules/@monaco-editor/react
npm ERR!   dev @monaco-editor/react@"4.2.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /root/.npm/_logs/2023-04-21T10_10_42_361Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-04-21T10_10_42_361Z-debug-0.log
 安装依赖...
fetch https://mirrors.aliyun.com/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.aliyun.com/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
OK: 497 MiB in 181 packages
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   dev react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @monaco-editor/react@4.2.1
npm ERR! node_modules/@monaco-editor/react
npm ERR!   dev @monaco-editor/react@"4.2.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /root/.npm/_logs/2023-04-21T10_10_56_969Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-04-21T10_10_56_969Z-debug-0.log
 安装依赖...
fetch https://mirrors.aliyun.com/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.aliyun.com/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
(1/4) Installing libjpeg-turbo (2.1.4-r0)
(2/4) Installing libjpeg-turbo-dev (2.1.4-r0)
(3/4) Installing jpeg-dev (9e-r0)
(4/4) Installing python3-dev (3.10.11-r0)
Executing busybox-1.35.0-r29.trigger
OK: 545 MiB in 185 packages

**Comment by 886k** [comment]
<img width="866" alt="image" src="https://user-images.githubusercontent.com/115762192/233758435-531977a7-7e79-4303-9527-9089aab94757.png">

**Comment by lzkgbld** [comment]
可以参考一下我这个地址的解决方案[跳转](https://github.com/FlechazoPh/QLDependency/issues/45#issuecomment-1567100351)

**Comment by FlechazoPh** [comment]
> 可以参考一下我这个地址的解决方案[跳转](https://github.com/FlechazoPh/QLDependency/issues/45#issuecomment-1567100351)
