### ISSUE TITLE
node版本

### ISSUE THREAD

**Issue by ATCThunder** [FlechazoPh/QLDependency#47]
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: npm@10.1.0
npm ERR! notsup Not compatible with your version of node/npm: npm@10.1.0
npm ERR! notsup Required: {"node":"^18.17.0 || >=20.5.0"}
npm ERR! notsup Actual:   {"npm":"9.6.7","node":"v18.16.0"}

我执行的时候报这个错，然后我用nvm下载了一个18.17.1的版本它还是显示老的node版本，不知道是什么原因

**Comment by ATCThunder** [comment]
sh: 当前node版本(如果没有node，请自行安装): : not found
v18.16.0

sh: 当前npm版本(如果没有npm，请自行安装): : not found
9.6.7
Nothing to stop. No server is running for the store at /root/.local/share/pnpm/store/v3
The location of the currently running pnpm differs from the location where pnpm will be installed
 Current pnpm location: /usr/local/bin
 Target location: /root/.local/share/pnpm

 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Already up to date
Progress: resolved 214, reused 192, downloaded 0, added 0, done
Done in 4.4s
Lockfile is up to date, resolution step is skipped
Already up to date
Done in 2.1s
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: npm@10.1.0
npm ERR! notsup Not compatible with your version of node/npm: npm@10.1.0
npm ERR! notsup Required: {"node":"^18.17.0 || >=20.5.0"}
npm ERR! notsup Actual:   {"npm":"9.6.7","node":"v18.16.0"}

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-09-11T05_35_54_614Z-debug-0.log
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Already up to date
 WARN  js-base64 has no binaries
 WARN  silly-datetime has no binaries
Progress: resolved 214, reused 192, downloaded 0, added 0, done
Done in 3.9s
Looking in indexes: https://pypi.doubanio.com/simple/
Requirement already satisfied: requests in /usr/local/lib/python3.10/site-packages (2.30.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/site-packages (from requests) (3.1.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests) (2.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests) (2023.5.7)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
sh: cd: line 59: can't cd to /ql/scripts/: No such file or directory
fetch https://mirrors.aliyun.com/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.aliyun.com/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
OK: 1021 MiB in 210 packages
sh: cd: line 61: can't cd to scripts: No such file or directory
OK: 1021 MiB in 210 packages

**Comment by Buliet** [comment]
> 我执行的时候报这个错，然后我用nvm下载了一个18.17.1的版本它还是显示老的node版本，不知道是什么原因

### 永久设置 node 版本
nvs link 18.17.1

<br>

> sh: cd: line 59: can't cd to /ql/scripts/: No such file or directory

脚本中还有个错误
青龙更新后，目录调整为 /ql/data/scripts/
所以将 脚本中的目录  /ql/scripts/ 改成 /ql/data/scripts/

**Comment by FlechazoPh** [comment]
> > 我执行的时候报这个错，然后我用nvm下载了一个18.17.1的版本它还是显示老的node版本，不知道是什么原因
> 
> ### 永久设置 node 版本
> nvs link 18.17.1
> 
> 
> > sh: cd: line 59: can't cd to /ql/scripts/: No such file or directory
> 
> 脚本中还有个错误 青龙更新后，目录调整为 /ql/data/scripts/ 所以将 脚本中的目录 /ql/scripts/ 改成 /ql/data/scripts/
