### ISSUE TITLE
cd: /ql: No such file or directory

### ISSUE THREAD

**Issue by prajna0** [FlechazoPh/QLDependency#5]
cd ql就没有问题
cd /ql进不去

**Comment by FlechazoPh** [comment]
什么环境，qinglong什么版本

**Comment by prajna0** [comment]
青龙2.10.2
系统:CentOS 7.9.2009 x86_64(Py3.7.9)

**Comment by FlechazoPh** [comment]
进入容器，安装一下 npm，输入ls 看下目录结构

**Comment by prajna0** [comment]
npm安装过了
![](https://user-images.githubusercontent.com/11697277/142392356-63d0b379-8e3e-41dc-8fa2-bc5f8ca55ec0.png)

**Comment by FlechazoPh** [comment]
> npm安装过了
> ![](https://user-images.githubusercontent.com/11697277/142392356-63d0b379-8e3e-41dc-8fa2-bc5f8ca55ec0.png)

你这个没进入容器，输入 docker exec -it 容器名 bash，进入容器再执行命令

**Comment by prajna0** [comment]
![](https://user-images.githubusercontent.com/11697277/142563468-faae8992-1dc3-49a8-9553-793c1e228099.png)

**Comment by FlechazoPh** [comment]
在这个地方执行  sh https://ghproxy.com/https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/QLOneKeyDependency.sh

**Comment by prajna0** [comment]
![](https://user-images.githubusercontent.com/11697277/142570659-20f78fda-268b-485b-af3c-f53594cb38ab.png)

**Comment by FlechazoPh** [comment]
直接把脚本下载下来复制到青龙里执行吧

**Comment by prajna0** [comment]
![](https://user-images.githubusercontent.com/11697277/142610456-d6e7e0a1-786e-44b4-9d2f-a065c7c942e5.png)

大佬还是不行

**Comment by FlechazoPh** [comment]
这个是因为没有npm，你搜下怎么安装 npm

**Comment by FlechazoPh** [comment]
其实2.10.2 以下就不用装，运行也不会报错，2.10.2以上才需要单独装依赖。

**Comment by kiddin9** [comment]
同样的问题, openwrt
![image](https://user-images.githubusercontent.com/48883331/142718859-da9abd7d-de4a-4fb0-8fc8-d328e767707c.png)
![image](https://user-images.githubusercontent.com/48883331/142718911-6019c20d-545e-4935-b4c1-1c9d64eb4f1c.png)

**Comment by naiveclub** [comment]
> 同样的问题, openwrt ![image](https://user-images.githubusercontent.com/48883331/142718859-da9abd7d-de4a-4fb0-8fc8-d328e767707c.png) ![image](https://user-images.githubusercontent.com/48883331/142718911-6019c20d-545e-4935-b4c1-1c9d64eb4f1c.png)

同问题，2.10.8的青龙都不知道怎么装依赖了。。。。。进容器装几乎都报错

**Comment by naiveclub** [comment]
解决了，要先安装npm和node
1、cd /usr/local  && wget https://nodejs.org/dist/v14.17.5/node-v14.17.5-linux-x64.tar.xz    
2、xz -dk node-v14.17.5-linux-x64.tar.xz  && tar -xvf node-v14.17.5-linux-x64.tar   
3、复制下面放到profile文件
export NODE_HOME=/usr/local/node-v14.17.5-linux-x64
export PATH=$PATH:$NODE_HOME/bin
export NODE_PATH=$NODE_HOME/lib/node_modules
 
生效
source /etc/profile
4、然后docker exec -it 容器名 bash
5、curl -fsSL https://ghproxy.com/https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/QLOneKeyDependency.sh | sh
运行这个命令就可以了

之前就算装了npm和node，直接运行一键命令还是会报错，今天换了这个方法，先进容器再运行就没啥问题，不过还是有两个地方报错了
![QQ截图20211121150318](https://user-images.githubusercontent.com/94167806/142753005-6fbdf1f0-437a-43b8-a073-4606fc4205f3.png)
图中提到的日志保存文件目录/root/.npm/    我在宝塔里面没有找到，日志文件也没有搜索到

**Comment by zailushang2008** [comment]
> 5、

我用了这个方法还是不行。

**Comment by rnadow** [comment]
> 
试试青龙里面新建任务
ql raw https://ghproxy.com/https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/QLOneKeyDependency.sh
