### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by coolzhi** [FlechazoPh/QLDependency#8]
root@ZHINAS:~# docker exec -it QL bash -c "$(curl -fsSL https://raw.githubusercontent.com/FlechazoPh/QLDependency/main/Shell/QLOneKeyDependency.sh | sh)"
sh: line 40: 当前node版本(如果没有node，请自行安装): : command not found
sh: line 41: npm: command not found
sh: line 44: 当前npm版本(如果没有npm，请自行安装): : command not found
sh: line 45: npm: command not found
sh: line 47: npm: command not found
sh: line 48: cd: /ql: No such file or directory
sh: line 49: pnpm: command not found
sh: line 51: pnpm: command not found
sh: line 53: npm: command not found
sh: line 55: npm: command not found
sh: line 57: npm: command not found
sh: line 59: npm: command not found
sh: line 61: npm: command not found
sh: line 63: npm: command not found
sh: line 65: npm: command not found
sh: line 67: npm: command not found
sh: line 69: npm: command not found
sh: line 71: npm: command not found
sh: line 73: npm: command not found
sh: line 75: npm: command not found
sh: line 77: npm: command not found
sh: line 79: npm: command not found
sh: line 81: npm: command not found
sh: line 83: npm: command not found
sh: line 85: pnpm: command not found
sh: line 87: pnpm: command not found
sh: line 89: pnpm: command not found
sh: line 91: pip3: command not found
sh: line 93: cd: /ql/scripts/: No such file or directory
sh: line 94: cd: /ql: No such file or directory
sh: line 95: apk: command not found
sh: line 96: cd: /ql: No such file or directory
sh: line 97: apk: command not found
bash: line 3: $'\E[36m\E[0m': command not found
bash: line 3: $'1m安装依赖...\E[0m': command not found
bash: line 5: $'\E[36m\E[0m': command not found
bash: line 5: $'1m安装依赖需要时间，请耐心等待!\E[0m': command not found
bash: line 12: $'\E[36m\E[0m': command not found
bash: line 12: 1m依赖安装完毕...建议重启: command not found
bash: line 14: $'\E[36m\E[0m': command not found
bash: line 14: 1m有任何问题，请在此仓库提交Issue：: command not found

**Comment by FlechazoPh** [comment]
![image](https://user-images.githubusercontent.com/94276146/143558929-ecc26127-e7c0-46d7-96e1-141cbd6912ae.png)
看日志，请先自行安装 node 和 npm 环境

**Comment by coolzhi** [comment]
有node 和npm环境
青龙里面手动安装没问题
用这个就不行~

**Comment by FlechazoPh** [comment]
可能是node路径不一致导致的
